import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1759746596876 implements MigrationInterface {
    name = 'AutoGenerated1759746596876'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "webinarLink"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "preferedLanguage"`);
        await queryRunner.query(`DROP TYPE "public"."webinars_preferedlanguage_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "fullName" character varying(160)`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "webinarName" character varying(360)`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "phoneNumber" character varying(15)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "phoneNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "webinarName"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "fullName"`);
        await queryRunner.query(`CREATE TYPE "public"."webinars_preferedlanguage_enum" AS ENUM('english', 'hindi')`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "preferedLanguage" "public"."webinars_preferedlanguage_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "webinarLink" character varying(2083)`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "name" character varying(160)`);
    }

}
