import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1759553264009 implements MigrationInterface {
    name = 'AutoGenerated1759553264009'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "webinarLink"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "preferedLanguage"`);
        await queryRunner.query(`DROP TYPE "public"."webinars_preferedlanguage_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "fullName" character varying(160)`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "webinarName" character varying(360)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpCode" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpExpiresat" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpAttempts" smallint DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpLastsentat" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpVerified" boolean DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."otp_type_enum" AS ENUM('email_verification', 'password_reset', 'login')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "otpType" "public"."otp_type_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "phoneNumber" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "CHK_user_otp_attempts" CHECK ("otpAttempts" <= 5 OR "otpAttempts" IS NULL)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "CHK_user_otp_attempts"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "phoneNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpType"`);
        await queryRunner.query(`DROP TYPE "public"."otp_type_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpVerified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpLastsentat"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpAttempts"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpExpiresat"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "otpCode"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "webinarName"`);
        await queryRunner.query(`ALTER TABLE "webinars" DROP COLUMN "fullName"`);
        await queryRunner.query(`CREATE TYPE "public"."webinars_preferedlanguage_enum" AS ENUM('english', 'hindi')`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "preferedLanguage" "public"."webinars_preferedlanguage_enum"`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "webinarLink" character varying(2083)`);
        await queryRunner.query(`ALTER TABLE "webinars" ADD "name" character varying(160)`);
    }

}
